name: Hello Actions

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: 
      ["master"]
  pull_request:
    types: 
      ["closed"]

env:
  name: CarlosThompson

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      name: C Thompson

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Run a one-line script
        run: echo Hello, $name!

  pull_request_only:
      runs-on: ubuntu-latest
      if: github.event_name == 'pull_request'
      needs: build
      steps:
        - name: Run a multi-line script
          run: |
            echo Add other actions to build,
            echo test, and deploy your project.
            echo Hi, $name.
